Create directory for unicorn service configuration, fix upgrade cmd
* The upgrade command in this multi-server example was broken because
  it did wait 60 seconds for the previous process to die before trying
  to spawn a new instance. This would cause the upgrade command to
  fail, defeating its purpoe

diff --git a/roles/unicorn/files/unicorn b/roles/unicorn/files/unicorn
--- a/roles/unicorn/files/unicorn
+++ b/roles/unicorn/files/unicorn
@@ -26,6 +26,8 @@
 #
 # /etc/init.d/unicorn start /etc/unicorn/my_app.conf
 
+TIMEOUT=${TIMEOUT-60}
+
 set -e
 
 sig () {
@@ -58,10 +60,26 @@ cmd () {
       $CMD
       ;;  
     upgrade)
-      sig USR2 && echo Upgraded && exit 0
-      echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+      printf 'Upgrading...'
+      if sig USR2 && sleep 10 && sig 0 && oldsig QUIT
+      then
+        n=$TIMEOUT
+        while test -s $OLD_PID && test $n -ge 0
+        do
+          printf '.' && sleep 1 && n=$(( $n - 1 ))
+        done
+        if test $n -lt 0 && test -s $OLD_PID
+        then
+          echo
+          echo >&2 "$OLD_PID still exists after $TIMEOUT seconds"
+          exit 1
+        fi
+        echo "...complete."
+        exit 0
+      fi
+      echo >&2 "Couldn't upgrade, starting instead"
       $CMD
-      ;;  
+      ;;
     rotate)
             sig USR1 && echo rotated logs OK && exit 0
             echo >&2 "Couldn't rotate logs" && exit 1
@@ -80,7 +98,7 @@ setup () {
   export PID=$RAILS_ROOT/tmp/pids/unicorn.pid
   export OLD_PID="$PID.oldbin"
 
-  CMD="/usr/bin/unicorn_rails -c config/unicorn.rb -E $RAILS_ENV -D"
+  CMD="/usr/local/bin/bundle exec unicorn_rails -c config/unicorn.rb -E $RAILS_ENV -D"
 }
 
 start_stop () {
